
# Author: Dashie
# Version: 1.0

# This is where the dankness is at!

properties:
    permissions:
        command-permission: 'strainables.command'
        consume-permission: 'strainables.consume'
    
    optionals:
        consume-cooldown: 8
    
    modifications:
        strain-lores:
            - "&aIt is time to get danked out!"
            - "&6420 Blaze it all!"
            - "&eGetting high as a cloud!"
    
    strains: "&aAvailable Strains: &5Birthday Cake Kush, OG Kush, Buddha Kush, Green Crack Kush, Gorilla Glue, Purple Haze, Silver Haze, Super Silver Haze, Purple Diesel, Strawberry Kush, Banana Kush, Water Melon Kush, Cookie Kush, Bubble Gum, Cheese, Afghan Kush, Dash Kush, Potato Salad Kush."
        