
# Author: Dashie
# Version: 1.0

main: dash.recoded.CatPawz

api-version: 1.13
version: 1.0

author: [Dashie, KvinneKraft]
name: CatPawz

commands:
    catpawz:
        aliases: [kittens, cats, fluffs, kittypawz]
