#
# Author: Dashie
# Version: 1.0
#
# These are all of the configurable permissions of the plugin:
next-gen-permissions:
  # This is the command required for the /rtp command:
  command-permission: default
  # This is the permission required for the /rtp reload
  # command and such:
  admin-permission: admin
  # This is the permission required for bypassing the
  # /rtp command cooldown (if any):
  cooldown-bypass-permission: bypass
# These are all of the configurable options of the plugin:
next-gen-rtp:
  #
  #
  teleportation:
    small-range:
      enabled: true
      range: 'x:1000 -x:-1000 z:1000 -z:1000'
      gui-item:
        material: IRON_BLOCK
        display-name: '&ateleport a 1000 blocks away'
        display-lore: '&aIt costs &e$5.000'
