
# Author: Dashie
# Version: 1.0

main: com.kvinnekraft.NextGenRTP

api-version: 1.15.2
version: 1.0

author: [Dashie, KvinneKraft, ME]
name: NextGenRTP

commands:
  rtp:
    aliases: [randomteleport, wild, wilderness, rand]
    description: by KvinneKraft yes.
