# Author: Dashie 
# Version: 1.0
death-tweaks:
    # The permission that is required
    # for /deathtweaks reload:
    admin-permission: 'admin'
    # All of the options for the potion 
    # effects which may be applied:
    potion-effects:
        # Should players gain a potion effect off of 
        # killing others:
        enabled: true
        # The potion effects which may be randomly chosen
        # based off of the chance:
        effects:
            - 'REGENERATION 2 10'
            - 'SPEED 2 10'
        # The chance that one of the above potion effects 
        # may be applied (1-100):
        chance: 60
        
    eternal-life:
        enabled: true
        
        mobs:
            - 'ZOMBIE'
            - 'SKELETON'
            
        
    
