
# Author: Dashie
# Version: 1.0

main: dash.recoded.DeathTweaks

api-version: 1.13
version: 1.0

name: DeathTweaks
author: [Dashie]

commands:
    deathtweaks:
        aliases: [dtw, dt, dashdeath, betterdeath]