
# Author : Dashie
# Version : 1.0


main: com.dashtp.Teleport

name: DashTPA
author: [Dashie, Dqu1J]

version: 1.2
api-version: 1.13

commands:
    dashtpa:
        aliases: [tpa, dashtpa]
        
    dashtp:
        aliases: [tp, dashtpo]
        
    dashtptoggle:
        aliases: [tptoggle, tpatoggle]