#
# Author: Dashie
# Version: 1.0
#
#
# You may modify these files, but if you would truly like to help me
# out, you can always donate to me at KvinneKraft@protonmail.com through
# PayPal. -Dashie
#
# ITEM_TYPES:
#   - CURRENCY
#   - 
#   -
#   -
#   -
#   -
#   -
#
crystals:
    1:
        buyCurrency: CURRENCY_TYPE_GOLD_COIN
        buyPrice: 10000
        #
        sellCurrency: CURRENCY_TYPE_GOLD_COIN
        sellPrice: 100
        #
        rewards:
            1:
                materialType: ITEM_TYPE_CURRENCY_GOLD_COIN
                materialAmount: 10000
                dropChance: 0.50
            2:
                materialType: ITEM_TYPE_CURRENCY_GOLD_COIN
                materialAmount: 10000
                dropChance: 0.50
            3:
                materialType: ITEM_TYPE_CURRENCY_GOLD_COIN
                materialAmount: 10000
                dropChance: 0.50
            4:
                materialType: ITEM_TYPE_CURRENCY_GOLD_COIN
                materialAmount: 10000
                dropChance: 40                
        #
        shopId: Shroom Crystal # Crystal name = Shop name without spaces + .gif
        shopTier: 5