# Author: Dashie
# Version: 1.0
global-tweaks:
  auto-reload: true
  reload-interval: 5
core-tweaks:
  bypass-permission: 'nopickupx.pickup'
  # some short documentation about the bellow code
  # eh, you can specify the material name, amount and
  # lore and name, that way you can be a bit more 
  # specific about that what should be allowed and 
  # that what should be disallowed.
  #
  # Now, the syntax seems pretty self explanatory, but
  # if you fail to understand what is going on, listen
  # up, the item:IRON_INGOT part basically specifies
  # the material name that should be blocked.
  #
  # The name:&aANY_NAME_WITH_COLORS specifies the name
  # the item must have in order to be seen as not allowed.
  # 
  # The same story with the lore, except, you can add multi
  # lines to it by using the '~' within the lore.
  # 
  # You can have up to three separate lines!
  blacklisted-items:
    - 'item:IRON_INGOT'
  notifications:
    send-to-player: true
    notify-interval: 3

