name: NoPickupX
version: ${project.version}
main: com.kvinnekraft.nopickupx.NoPickupX
api-version: 1.16
authors: [Dashie, KvinneKraft, ME]
description: Disable specific items from being picked up.
website: https://github.com/KvinneKraft
