
# Author: Dashie
# Version: 1.0

main: discordc.DiscordC

author: [Dashie]
name: DiscordC

version: 1.0
api-version: 1.8

commands:
    dev:
        aliases: [coder, developer]
        
    disc:
        aliases: [discord, discrd]