# Author: Dashie
# Version: 1.0
startup-tweaks:
  auto-reload: true
  reload-interval: 5
#
# (Potion Obtainables X Format Documentation)
#
# The number (1) as seen in the default config.yml
# is there so I can loop through all numbers and see
# which exist and go based off of that.  You may 
# add in more numbers, just make sure they are in 
# order (1, 2, 3...);
#
# The item: section basically contains custom attributes
# that you can set to your liking.  If you want to disable
# any of these options then you can simply leave them
# empty.
#
# The consumption: section basically contains all of the 
# configurable functionality on consumption.  Whenever a
# player tries to eat the specified item the corresponding
# configuration will be used.  For the commands, if you
# want the command to be executed as a player then you
# should put a '/' in front of the command, if you want
# the console to execute it you should put a '~' in front
# of the command.
#
# If you need some help finding enchantment names that are
# recognized by my code see some documentation here. (Use the names all caps)
# ENCHANTMENT NAMES 1.16x: https://www.digminecraft.com/lists/enchantment_list_pc.php
#
# And if you need some help finding potion effect names then
# you can find them here. (Use the names all caps)
# POTION EFFECT NAMES 1.16x: https://mcreator.net/wiki/potion-effect-ids
#
core-tweaks:
  potion-items:
    1:
      item:
        type: STICK
        name: '&aIntoxication'
        lore:
          - '&5I am lore.'
        enchantments:
          - 'SHARPNESS 5'
      consumption:
#check permission in list, if none skip check.
#also if op.
        permission: 'none'
        message: 'none'          
        effects:
          - 'SPEED 1 20'
        commands:
#check async list.get(id).split(" ")[0] == 
#e.getCommand()
          - '/kit pvp'
          - '~msg %p% &aYou ate a stick!'
  