
# Author: Dashie
# Version: 1.0

main: com.dashmobs.BetterMobs

name: DashBetterMobs
author: [Dashie]

version: 1.0
api-version: 1.13

commands:
    bettermobs:
        aliases: [dashmobs]
        description: Main command for Dash Mobs 1.0

