
# Future-Features:
# 
# - Permissions per Extension
# - 
# -

# Dashies Configuration File

plugin-messages:
    action-not-allowed: "&cYou are not supposed to do this!"
    
no-craft:
    enabled: true
    
    blacklisted-items:
        - 'HOPPER'
        - 'SHIELD'