# Author: Dashie
# Version: 1.0
name: QuickEatX
version: ${project.version}
main: com.kvinnekraft.quickeatx.QuickEatX
api-version: 1.16
authors: [Dashie, KvinneKraft, ME]
description: Yes.
website: https://github.com/KvinneKraft
