
main: com.dashiesxraynotifier.DashRays

author: [Dashie]
name: DashRays

version: 1.0
api-version: 1.7

commands:
    dashrays:
        aliases: [dashray, xray]
        description: Main command for Dash Rays