
# Author: Dashie
# Version: 1.0

main: dash.recoded.Captcha

version: 2.0
api-version: 1.13

name: BetterCaptcha
author: [Dashie, KvinneKraft, Freya, Princess_Freya, Majesty_Freya]

commands:
    dashcaptcha:
        aliases: [dc, captcha, dashrobot, robots, bettercaptcha]
        description: A magickal command