
# Author: Dashie
# Version: 1.0

main: com.kvinnekraft.FlamingArrows

version: 1.0
api-version: 1.13

name: FlamingArrows
author: [Dashie, KvinneKraft, Freya, AnyoneWhoHasBeenAPartOfMyLifeMuchLove]

commands:
    flamingarrows:
        aliases: [fa, arrows, breakglass, glassarrows, arrowglass]
        description: Flamy Arrows by KvinneKraft!