# Project: Master Boot Record Kill
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = Master_Boot_Record_Kill_private.res
OBJ      = "Master\ Boot\ Record.o" $(RES)
LINKOBJ  = "Master Boot Record.o" $(RES)
LIBS     = -L"C:/Dev-Cpp/MinGW64/lib32" -L"C:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -m32
INCS     = -I"C:/Dev-Cpp/MinGW64/include" -I"C:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Dev-Cpp/MinGW64/include" -I"C:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "../Master Boot Record Kill.exe"
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

"Master\ Boot\ Record.o": Master\ Boot\ Record.cpp
	$(CPP) -c "Master Boot Record.cpp" -o "Master Boot Record.o" $(CXXFLAGS)

Master_Boot_Record_Kill_private.res: Master_Boot_Record_Kill_private.rc 
	$(WINDRES) -i Master_Boot_Record_Kill_private.rc -F pe-i386 --input-format=rc -o Master_Boot_Record_Kill_private.res -O coff 

