# Author: Dashie
# Version: 1.0
name: KillReward
version: ${project.version}
main: com.kvinnekraft.killreward.KillReward
authors: [Dashie]
description: A lil sample
website: https://pugpawz.com

commands:
  KillReward:
    aliases: []
    description: Oh, what is this?
