
# Author: Dashie
# Version: 1.0

main: dash.recoded.BetterKits

api-version: 1.13
version: 1.0

author: [Dashie, KvinneKraft]
name: BetterKits

commands:
    betterkits:
        aliases: [betterkit, kits, kit, betterkawts]
        description: Fancy Kitterinos!