
# Dash Strict Configuration File-
#
#
# (To-Do List):
#
# - Command Blocker
# - Use Blocker
# - Fall Blocker
# - Craft Blocker
# - Message Delay
# - IP Restrictor
# - World Blocker
# - Word Blocker
# - Block Place Blocker
# - Command Support rather than Just Config
