
# Dash Strict Configuration File-
#
#
# (To-Do List):
#
# - Fall Blocker
# - Message Delay
# - IP Restrictor
# - World Blocker
# - Word Blocker
# - Block Place Blocker
# - Command Support rather than Just Config
# - Make imports look better


craft-blocker:
    enabled: false
    
    items:
        - 'ENCHANTMENT_TABLE'
        - 'FIRE_CHARGE'
        - 'ENDER_CHEST' 
        - 'HOPPER'
    
    denied-message: '&cYou do not have access to craft this.'
    bypass-permission: 'dashstrict.bypass'    
    
use-blocker:
    enabled: false
    
    blocks:
        - 'COMMAND_BLOCK'
        - 'BREWING_STAND'
    
    items:
        - 'ENDER_PEARL'
        
    denied-message: '&cYou do not have access to use this.'
    bypass-permission: 'dashstrict.bypass'

command-block:
    enabled: false
    
    commands:
        - '/ver'
        - '/pl'
        - '/about'
        - '/minecraft'
        - '/bukkit'
        
    denied-message: '&cYou do not have access to this command.'
    bypass-permission: 'dashstrict.bypass'

    