
#
# Dash Money Config File 1.0
#

properties:  
    friendly-mobs:
        enabled: true
        
        max-drop: 8
        min-drop: 1
        
        drop-head: false        
    
        receive-message: "&aYou have received &b%money%$ &afor killing a &b%entity% &a!"
    
    hostile-mobs:
        enabled: true
        
        max-drop: 20
        min-drop: 1
        
        drop-head: false
        
        receive-message: "&aYou have received &b%money%$ &afor killing a &b%entity% &a!"
        
    players:
        enabled: true
        
        max-drop: 1000
        min-drop: 100

        drop-head: true       
        
        receive-message: "&aYou have received &b%money%$ &afor killing a &b%entity% &a!"
        
    blocks:
        place-rewards:
            enabled: false
            
            blocks:
                - 'DIAMOND_ORE 65'
                - 'EMERALD_ORE 85'
                - 'GOLD_ORE 55'
            
            receive-message: "&aYou have received &b%money%$ &afor placing a &b%block% &a!"
            
        break-rewards:
            enabled: false
            
            blocks:
                - 'OBSIDIAN 100'
                - 'DIAMOND_ORE 65'
                - 'EMERALD_ORE 75'
        
            receive-message: "&aYou have received &b%money%$ &afor breaking a &b%block% &a!"