
# Author: Dashie
# Version: 1.0

main: com.weeds.Strains

name: DashStrains
author: [Dashie]

version: 1.0
api-version: 1.13

commands:
    dashstrains:
        aliases: [ds, weedz, weed, strainables, strains]
        description: This is a plugin about weed!