# Project: Encryptor
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = Encryptor_private.res
OBJ      = "tutorial\ -\ dash\ 5.o" $(RES)
LINKOBJ  = "tutorial - dash 5.o" $(RES)
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -m32 -pg
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "../Crypto Module.exe"
CXXFLAGS = $(CXXINCS) -m32 -pg -std=c++11
CFLAGS   = $(INCS) -m32 -pg -std=c++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

"tutorial\ -\ dash\ 5.o": tutorial\ -\ dash\ 5.cpp
	$(CPP) -c "tutorial - dash 5.cpp" -o "tutorial - dash 5.o" $(CXXFLAGS)

Encryptor_private.res: Encryptor_private.rc 
	$(WINDRES) -i Encryptor_private.rc -F pe-i386 --input-format=rc -o Encryptor_private.res -O coff 

