
# Author: Dashie
# Version: 1.0

main: com.dashitems.Rename

author: [Dashie]
name: DashRename

api-version: 1.8
version: 1.0

commands:
    fakeop:
        aliases: [fakeop, fop, fo]
        
    rename:
        aliases: [renameitem, ri]