
# Author: Dashie
# Version: 1.0

main: dash.recoded.Love

api-version: 1.13
version: 20

author: [Dashie, KvinneKraft, Freya]
name: BetterLove

commands:
    love:
        aliases: [betterlove, morelove, valentine, lov, luv, loveyou, ly]
        description: Love eachother!