
# Author: Dashie
# Version: 1.0

main: com.kvinnekraft.LuckyBlawks

api-version: 1.13
version: 1.0

author: [Dashie, KvinneKraft]
name: LuckyBlawks

commands:
  luckyblawks:
    aliases: [luckyblocks, luckyb, luckybloks, lb]
    description: Brought to you by KvinneKraft.