
# Author: Dashie
# Version: 1.0

properties:
    permissions:
        use-permission: 'dashbowz.crossbow.use'
        admin-permission: 'dashbowz.admin'
    
    effects:
        lightning-chance: 0.5
        lightning: true
        
        explosion-chance: 0.5
        explosion-break-blocks: false
        explosion: true
        
        fireworks-chance: 0.5
        fireworks: true
        
        poison-chance: 0.5
        poison: true
        
        wither-chance: 0.5
        wither: true
        
        hunger-chance: 0.5
        hunger: true
        
        rat-chance: 0.5
        rat: true
        
    bow-meta:
        display-lore: 
            - '&aA bow of mighty power!'
            
        display-name: '&e&lC&eross-&e&lB&eow'
            