
# Author: Dashie
# Version: 1.0

main: com.philosophy.Consilience

author: [Dashie]
name: DashConsilience

api-version: 1.8
version: 1.0

commands:
    spawn:
        aliases: [spon, worldspawn, spwn, sp]
        
    staff:
        aliases: [dev, mod, admin, list]
        
    discord:
        aliases: [disc]

