
# Author: Dashie
# Version: 1.0

main: com.dashcraft.DashChat

author: [Dashie]
name: DashHat

api-version: 1.13
version: 1.0

commands:
    dashhat:
        aliases: [hat, dh, dashiehat, dashhawt, head]

