
# Author: Dashie
# Version: 1.0

optional-properties:
    # The permission that is required in order to use the
    # admin commands that come with this plugin. (/dashsession)
    command-permission: 'dashsession.admin'
    
    # Allow people to type /dashsession in order to see who
    # has coded the plugin, this helps me out as a Programmer.
    developer-support: true

reward-properties:
    # The permission that is required in order to receive 
    # rewards.
    reward-permission: 'dashsession.reward'  
    
    # The interval in seconds in which people should receive
    # a reward. 
    reward-interval: 600
    
    # The message displayed when a player receives a reward.
    # Both through chat and on screen title. 
    reward-message: "&aYou have been rewarded for being online!"
    
    # Commands to execute along with their probability of being
    # actually executed (Format: <command> (chance):<chance 0.00000-1)):
    rewards:
        - 'give %player% GOLDEN_APPLE 1 name:&d&lApple (chance):0.001'
        - 'eco give %player% 500 (chance):0.05'
        - 'eco give %player% 10 (chance):0.9' 
        - 'eco give %player% 1000 (chance):0.005'