
main: com.dashcraft.CraftBlocker

name: DashCraftBlocker
author: [Dashie, KvinneKraft, ME]

version: 1.2
api-version: 1.16

commands:
    craftblocker:
        aliases: [craftblock, cb, dashblocker, dashblock]
        description: Main command for Dashies Craft Blocker plugin 1.2!